"""
Recovery Estimation

Estimates per-muscle recovery time based on training volume, intensity,
and autonomic readiness (ARI).  Used by the scheduler to prevent
programming a muscle group before it has adequately recovered.

Base recovery windows (hours):
    Large muscles  (back, quads, glutes, hamstrings, chest): 48-72 h
    Medium muscles (delts, triceps, biceps):                 36-48 h
    Small muscles  (calves, forearms, abs):                  24-36 h

CNS / Systemic Fatigue Model
-----------------------------
In addition to local muscle recovery, the module tracks systemic (CNS-level)
fatigue generated by a training session.  Heavy compound movements at high
RPE contribute disproportionately to systemic fatigue, which limits the
athlete's capacity to perform across subsequent sessions.

Key functions:
- ``compute_systemic_fatigue()`` — session-level systemic fatigue score (0-100).
- ``check_daily_fatigue_budget()`` — validates a planned session against daily
  CNS budget constraints (max high-RPE exercises, RPE-weighted compound cap).
- ``check_consecutive_heavy_days()`` — flags back-to-back sessions that both
  exceed a systemic fatigue threshold.
"""


# ---------------------------------------------------------------------------
# Recovery baselines (hours) — (minimum, maximum)
# ---------------------------------------------------------------------------

_RECOVERY_WINDOWS: dict[str, tuple[float, float]] = {
    # Large muscle groups
    "back":        (48.0, 72.0),
    "quads":       (48.0, 72.0),
    "glutes":      (48.0, 72.0),
    "hamstrings":  (48.0, 72.0),
    "chest":       (48.0, 72.0),
    # Medium muscle groups
    "front_delt":  (36.0, 48.0),
    "side_delt":   (36.0, 48.0),
    "rear_delt":   (36.0, 48.0),
    "triceps":     (36.0, 48.0),
    "biceps":      (36.0, 48.0),
    # Small muscle groups
    "calves":      (24.0, 36.0),
    "forearms":    (24.0, 36.0),
    "abs":         (24.0, 36.0),
}

# Fallback for unknown muscle groups.
_DEFAULT_WINDOW: tuple[float, float] = (48.0, 72.0)


# ---------------------------------------------------------------------------
# CNS / Systemic fatigue constants
# ---------------------------------------------------------------------------

# Movement patterns classified by CNS cost tier.
_HEAVY_COMPOUND_PATTERNS: set[str] = {
    "squat", "hinge", "deadlift", "hip_hinge", "knee_dominant",
}
_MEDIUM_COMPOUND_PATTERNS: set[str] = {
    "horizontal_push", "incline_push", "vertical_push",
    "horizontal_pull", "vertical_pull", "push", "pull", "row",
    "press", "compound",
}
_ISOLATION_PATTERNS: set[str] = {
    "isolation", "isolation_curl", "isolation_extension",
    "curl", "extension", "lateral", "fly", "raise",
}

# Fatigue multipliers per tier.
_FATIGUE_MULTIPLIER_HEAVY: float = 2.0
_FATIGUE_MULTIPLIER_MEDIUM: float = 1.0
_FATIGUE_MULTIPLIER_ISOLATION: float = 0.3

# Daily CNS budget limits.
_MAX_HIGH_RPE_EXERCISES: int = 2         # Max exercises at RPE 8+
_MAX_COMPOUND_RPE_WEIGHTED_SETS: float = 40.0  # e.g. 5 sets x RPE 8 = 40
_MAX_FATIGUE_BUDGET: float = 100.0       # Normalization ceiling

# Consecutive-day fatigue threshold.
_CONSECUTIVE_HEAVY_THRESHOLD: float = 70.0


# ---------------------------------------------------------------------------
# Public API — local muscle recovery
# ---------------------------------------------------------------------------

def estimate_recovery_time(
    muscle_group: str,
    volume: int,
    intensity: float,
    ari: float,
) -> float:
    """
    Estimate recovery time in hours for a muscle group after a session.

    The estimate starts from the muscle's base recovery window and is
    modified by:

    * **Volume factor**: each set beyond a moderate baseline (4 sets)
      adds ~5 % to recovery time.
    * **Intensity factor**: higher intensity (RPE / percentage of 1-RM,
      expressed 0-1) increases recovery; 1.0 = maximal.
    * **ARI factor**: poor readiness (low ARI) lengthens recovery because
      the athlete is already under-recovered.

    Args:
        muscle_group: Name of the muscle (must match keys in the recovery
                      windows table, case-insensitive).
        volume: Working sets performed for this muscle in the session.
        intensity: Intensity metric in [0, 1] (e.g. avg RPE / 10 or
                   % 1-RM expressed as a decimal).
        ari: Current Autonomic Readiness Index (0-100).

    Returns:
        Estimated recovery time in hours, rounded to one decimal.
    """
    base_min, base_max = _RECOVERY_WINDOWS.get(
        muscle_group.lower(), _DEFAULT_WINDOW,
    )

    # Interpolate within the window based on intensity.
    clamped_intensity = max(0.0, min(1.0, intensity))
    base_hours = base_min + (base_max - base_min) * clamped_intensity

    # Volume modifier: +5% per set above a 4-set baseline.
    volume_factor = 1.0 + max(0, volume - 4) * 0.05

    # ARI modifier: low ARI lengthens recovery (inverse relationship).
    # ARI 100 -> modifier 0.85 (slightly faster), ARI 0 -> modifier 1.30.
    clamped_ari = max(0.0, min(100.0, ari))
    ari_factor = 1.30 - (clamped_ari / 100.0) * 0.45

    recovery_hours = base_hours * volume_factor * ari_factor
    return round(recovery_hours, 1)


def can_train_muscle(
    muscle_group: str,
    hours_since_last: float,
    recovery_hours_needed: float,
) -> bool:
    """
    Determine whether a muscle group has recovered enough to train again.

    Args:
        muscle_group: Target muscle (used for logging/context; the
                      comparison is purely numeric).
        hours_since_last: Hours elapsed since the muscle was last trained.
        recovery_hours_needed: Required recovery hours (typically the
                               output of :func:`estimate_recovery_time`).

    Returns:
        ``True`` if *hours_since_last* >= *recovery_hours_needed*.
    """
    return hours_since_last >= recovery_hours_needed


def get_recovery_window(muscle_group: str) -> tuple[float, float]:
    """
    Return the base recovery window (min_hours, max_hours) for a muscle.

    Args:
        muscle_group: Muscle name (case-insensitive).

    Returns:
        Tuple of (min_hours, max_hours).  Falls back to (48, 72) for
        unknown muscle groups.
    """
    return _RECOVERY_WINDOWS.get(muscle_group.lower(), _DEFAULT_WINDOW)


# ---------------------------------------------------------------------------
# Public API — CNS / systemic fatigue
# ---------------------------------------------------------------------------

def _classify_fatigue_tier(movement_pattern: str) -> str:
    """
    Classify a movement pattern into a fatigue tier.

    Returns one of ``"heavy"``, ``"medium"``, or ``"isolation"``.
    """
    pattern = movement_pattern.lower().strip()
    if pattern in _HEAVY_COMPOUND_PATTERNS:
        return "heavy"
    if pattern in _MEDIUM_COMPOUND_PATTERNS:
        return "medium"
    if pattern in _ISOLATION_PATTERNS:
        return "isolation"
    # Heuristic fallback: if it contains common compound keywords, treat
    # as medium; otherwise default to isolation.
    for keyword in ("squat", "dead", "hinge"):
        if keyword in pattern:
            return "heavy"
    for keyword in ("press", "row", "pull", "push", "compound"):
        if keyword in pattern:
            return "medium"
    return "isolation"


def compute_systemic_fatigue(
    session_exercises: list[dict],
) -> float:
    """
    Compute a systemic (CNS-level) fatigue score for a training session.

    Each exercise dict must contain:
        - ``movement_pattern`` (str): e.g. ``"squat"``, ``"horizontal_push"``,
          ``"isolation_curl"``.
        - ``sets`` (int): number of working sets.
        - ``rpe`` (float): average RPE for the exercise (1-10 scale).

    Scoring:
        - Heavy compounds (squat, hinge, etc.) at RPE > 8:
          ``sets * RPE * 2.0``
        - Medium compounds (RPE 6-8):
          ``sets * RPE * 1.0``
        - Isolation movements:
          ``sets * RPE * 0.3``

    The raw total is normalized against :data:`_MAX_FATIGUE_BUDGET` and
    capped at 100.

    Args:
        session_exercises: List of exercise dicts.

    Returns:
        Fatigue score in [0, 100], rounded to one decimal.
    """
    total_fatigue = 0.0

    for ex in session_exercises:
        pattern = ex.get("movement_pattern", "isolation")
        sets = ex.get("sets", 0)
        rpe = ex.get("rpe", 5.0)

        tier = _classify_fatigue_tier(pattern)

        if tier == "heavy" and rpe > 8:
            multiplier = _FATIGUE_MULTIPLIER_HEAVY
        elif tier == "heavy":
            # Heavy pattern but moderate RPE — treat as medium
            multiplier = _FATIGUE_MULTIPLIER_MEDIUM
        elif tier == "medium":
            multiplier = _FATIGUE_MULTIPLIER_MEDIUM
        else:
            multiplier = _FATIGUE_MULTIPLIER_ISOLATION

        total_fatigue += sets * rpe * multiplier

    score = (total_fatigue / _MAX_FATIGUE_BUDGET) * 100.0
    return round(min(score, 100.0), 1)


def check_daily_fatigue_budget(
    planned_exercises: list[dict],
) -> dict:
    """
    Validate whether a planned session stays within the daily CNS budget.

    Budget rules:
        1. **Max 2 exercises at RPE 8+** per session.
        2. **Max combined RPE-weighted compound sets of 40**
           (e.g. 5 sets at RPE 8 = 40).

    Each exercise dict should contain ``movement_pattern``, ``sets``, and
    ``rpe`` keys.

    Returns:
        Dict with keys:
            - ``within_budget`` (bool): ``True`` if all constraints met.
            - ``fatigue_score`` (float): systemic fatigue score (0-100).
            - ``warnings`` (list[str]): human-readable constraint violations.
    """
    warnings: list[str] = []

    # Count exercises at RPE 8+
    high_rpe_count = 0
    compound_rpe_weighted = 0.0

    for ex in planned_exercises:
        pattern = ex.get("movement_pattern", "isolation")
        sets = ex.get("sets", 0)
        rpe = ex.get("rpe", 5.0)

        tier = _classify_fatigue_tier(pattern)

        if rpe >= 8.0:
            high_rpe_count += 1

        # Only compound movements count toward the compound RPE-weighted cap
        if tier in ("heavy", "medium"):
            compound_rpe_weighted += sets * rpe

    if high_rpe_count > _MAX_HIGH_RPE_EXERCISES:
        warnings.append(
            f"Too many high-RPE exercises: {high_rpe_count} "
            f"(max {_MAX_HIGH_RPE_EXERCISES} at RPE 8+)"
        )

    if compound_rpe_weighted > _MAX_COMPOUND_RPE_WEIGHTED_SETS:
        warnings.append(
            f"Compound RPE-weighted sets too high: {compound_rpe_weighted:.0f} "
            f"(max {_MAX_COMPOUND_RPE_WEIGHTED_SETS:.0f})"
        )

    fatigue_score = compute_systemic_fatigue(planned_exercises)

    return {
        "within_budget": len(warnings) == 0,
        "fatigue_score": fatigue_score,
        "warnings": warnings,
    }


def check_consecutive_heavy_days(
    previous_session_fatigue: float,
    current_fatigue: float,
) -> dict:
    """
    Flag whether two consecutive training sessions both exceed the systemic
    fatigue threshold.

    Back-to-back heavy sessions impair CNS recovery and increase injury risk.

    Args:
        previous_session_fatigue: Systemic fatigue score (0-100) from the
                                  most recent prior session.
        current_fatigue: Systemic fatigue score (0-100) for the current /
                         planned session.

    Returns:
        Dict with keys:
            - ``consecutive_heavy`` (bool): ``True`` if both sessions exceed
              the threshold of 70.
            - ``recommendation`` (str): actionable guidance.
    """
    both_heavy = (
        previous_session_fatigue >= _CONSECUTIVE_HEAVY_THRESHOLD
        and current_fatigue >= _CONSECUTIVE_HEAVY_THRESHOLD
    )

    if both_heavy:
        recommendation = (
            "Two consecutive high-fatigue sessions detected "
            f"(previous: {previous_session_fatigue:.0f}, "
            f"current: {current_fatigue:.0f}). "
            "Consider inserting a lighter session, swapping exercise order, "
            "or reducing RPE/volume on one of the days to allow CNS recovery."
        )
    else:
        recommendation = "Consecutive session fatigue is within acceptable limits."

    return {
        "consecutive_heavy": both_heavy,
        "recommendation": recommendation,
    }
