import io
from datetime import date

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse, PlainTextResponse
from sqlalchemy import select, desc
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import get_current_user
from app.models.user import User
from app.models.diagnostic import PDSLog, HQILog
from app.models.measurement import BodyWeightLog, SkinfoldMeasurement
from app.models.training import TrainingProgram
from app.models.nutrition import NutritionPrescription

router = APIRouter(prefix="/export", tags=["export"])


@router.get("/report")
async def export_report(
    user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    today = date.today()

    pds_result = await db.execute(
        select(PDSLog).where(PDSLog.user_id == user.id)
        .order_by(desc(PDSLog.recorded_date), desc(PDSLog.created_at)).limit(1)
    )
    pds = pds_result.scalar_one_or_none()

    hqi_result = await db.execute(
        select(HQILog).where(HQILog.user_id == user.id)
        .order_by(desc(HQILog.recorded_date), desc(HQILog.created_at)).limit(1)
    )
    hqi = hqi_result.scalar_one_or_none()

    bw_result = await db.execute(
        select(BodyWeightLog).where(BodyWeightLog.user_id == user.id)
        .order_by(desc(BodyWeightLog.recorded_date), desc(BodyWeightLog.created_at)).limit(1)
    )
    bw = bw_result.scalar_one_or_none()

    sf_result = await db.execute(
        select(SkinfoldMeasurement).where(SkinfoldMeasurement.user_id == user.id)
        .order_by(desc(SkinfoldMeasurement.recorded_date), desc(SkinfoldMeasurement.created_at)).limit(1)
    )
    sf = sf_result.scalar_one_or_none()

    prog_result = await db.execute(
        select(TrainingProgram)
        .where(TrainingProgram.user_id == user.id, TrainingProgram.is_active == True)
        .order_by(desc(TrainingProgram.created_at)).limit(1)
    )
    program = prog_result.scalar_one_or_none()

    rx_result = await db.execute(
        select(NutritionPrescription)
        .where(NutritionPrescription.user_id == user.id, NutritionPrescription.is_active == True)
        .order_by(desc(NutritionPrescription.created_at)).limit(1)
    )
    rx = rx_result.scalar_one_or_none()

    # Top 3 lagging muscles (lowest HQI scores)
    lagging = []
    if hqi and hqi.site_scores:
        sorted_sites = sorted(hqi.site_scores.items(), key=lambda x: x[1])
        lagging = sorted_sites[:3]

    # Build report text
    lines = [
        f"Coronado Physique Report — {user.username} — {today}",
        "=" * 60,
        "",
        "PDS SCORE",
        "-" * 30,
    ]
    if pds:
        lines.append(f"  Score: {pds.pds_score:.1f}")
        lines.append(f"  Tier:  {pds.tier or 'N/A'}")
        lines.append("  Components:")
        for comp, val in (pds.component_scores or {}).items():
            lines.append(f"    {comp}: {val:.1f}")
    else:
        lines.append("  No PDS data recorded yet.")

    lines += ["", "BODY COMPOSITION", "-" * 30]
    if bw:
        lines.append(f"  Current Weight: {bw.weight_kg} kg")
    else:
        lines.append("  No body weight data.")
    if sf and sf.body_fat_pct:
        lines.append(f"  Body Fat: {sf.body_fat_pct:.1f}%")
        if bw:
            lbm = round(bw.weight_kg * (1 - sf.body_fat_pct / 100), 1)
            lines.append(f"  Lean Mass: {lbm} kg")

    lines += ["", "TOP 3 LAGGING MUSCLE GROUPS (HQI)", "-" * 30]
    if lagging:
        for site, score in lagging:
            lines.append(f"  {site}: HQI {score:.1f}")
    else:
        lines.append("  No HQI data recorded yet.")

    lines += ["", "TRAINING PROGRAM", "-" * 30]
    if program:
        lines.append(f"  Name:       {program.name}")
        lines.append(f"  Split:      {program.split_type}")
        lines.append(f"  Days/Week:  {program.days_per_week}")
        lines.append(f"  Week:       {program.current_week} / {program.mesocycle_weeks}")
    else:
        lines.append("  No active program.")

    lines += ["", "MACRO PRESCRIPTION", "-" * 30]
    if rx:
        lines.append(f"  Phase:    {rx.phase}")
        lines.append(f"  Calories: {int(rx.target_calories)} kcal")
        lines.append(f"  Protein:  {rx.protein_g} g")
        lines.append(f"  Carbs:    {rx.carbs_g} g")
        lines.append(f"  Fat:      {rx.fat_g} g")
    else:
        lines.append("  No active prescription.")

    lines += ["", "=" * 60, "Generated by Coronado v4.0"]

    report_text = "\n".join(lines)

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.units import inch

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter,
                                leftMargin=inch, rightMargin=inch,
                                topMargin=inch, bottomMargin=inch)
        styles = getSampleStyleSheet()
        story = []

        for line in lines:
            if line.startswith("="):
                story.append(Spacer(1, 0.05 * inch))
            elif line.startswith("-"):
                story.append(Spacer(1, 0.02 * inch))
            elif line == "":
                story.append(Spacer(1, 0.1 * inch))
            elif line.startswith("Coronado Physique Report"):
                story.append(Paragraph(line, styles["Title"]))
            elif not line.startswith(" ") and line:
                story.append(Paragraph(f"<b>{line}</b>", styles["Heading2"]))
            else:
                story.append(Paragraph(line.strip(), styles["Normal"]))

        doc.build(story)
        buf.seek(0)

        return StreamingResponse(
            buf,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=coronado_report_{today}.pdf"},
        )
    except ImportError:
        return PlainTextResponse(
            content=report_text,
            headers={"Content-Disposition": f"attachment; filename=coronado_report_{today}.txt"},
        )
