"""initial_schema

Revision ID: 7850f1556da9
Revises: 
Create Date: 2026-03-18 23:43:38.942507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7850f1556da9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_exercises_muscle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('training_sessions', 'stale_baselines',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('training_sets', 'is_warmup',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_sets', 'is_warmup',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('training_sessions', 'stale_baselines',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.alter_column('exercises', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
