"""add_profile_preferences_and_exercise_fields

Revision ID: d6e44051452a
Revises: c047a75d24f4
Create Date: 2026-03-19 21:38:41.187150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6e44051452a'
down_revision: Union[str, None] = 'c047a75d24f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('movement_pattern_detail', sa.String(length=50), nullable=True))
    op.add_column('exercises', sa.Column('contraindications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('exercises', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_exercises_muscle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_foreign_key(None, 'exercises', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('training_sessions', 'stale_baselines',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('training_sets', 'is_warmup',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('user_profiles', sa.Column('available_equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('disliked_exercises', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('injury_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_profiles', sa.Column('cycle_tracking_enabled', sa.Boolean(), nullable=False))
    op.add_column('user_profiles', sa.Column('cycle_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'cycle_start_date')
    op.drop_column('user_profiles', 'cycle_tracking_enabled')
    op.drop_column('user_profiles', 'injury_history')
    op.drop_column('user_profiles', 'disliked_exercises')
    op.drop_column('user_profiles', 'available_equipment')
    op.alter_column('training_sets', 'is_warmup',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('training_sessions', 'stale_baselines',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.alter_column('exercises', 'is_custom',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('exercises', 'contraindications')
    op.drop_column('exercises', 'movement_pattern_detail')
    # ### end Alembic commands ###
